[project]
name = "us-routing"
version = "0.1.0"
description = "US Routing is a Python library for fast local routing in the United States. Useful when approximations are acceptable."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "ivanbelenky", email = "ivandietert@gmail.com" },
]
dependencies = [
    "networkx>=3.3",
    "pandas>=2.2.2",
    "numpy>=2.1.0",
    "scipy>=1.14.1",
    "pydantic>=2.8.2",
    "geopandas>=1.0.1",
    "shapely>=2.0.0",
    "tqdm>=4.66.5",
    "requests>=2.32.3",
    "rtree>=1.3.0",
    "uszipcode>=1.0.1",
    "sqlalchemy-mate==2.0.0",
    "python-levenshtein>=0.25.1",
]

[project.urls]
Homepage = "https://github.com/ivanbelenky/us-routing"

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.2",
    "ipython>=8.27.0",
    "openpyxl>=3.1.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["us_routing"]

[tool.pytest.ini_options]
testpaths = ["tests"]
